project:
  type: website
  output-dir: docs

website:
  title: "Danyal's Blog"
  favicon: icon.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mdanyalmalik
      - icon: linkedin
        href: https://linkedin.com/in/mdanyalmalik
format:
  html:
    theme: lux
    css: styles.css



