project:
  type: website
  output-dir: docs

website:
  title: "Danyal's Blog"
  favicon: icon.png
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/_danyalmalik
      - icon: linkedin
        href: https://linkedin.com/in/mdanyalmalik
      - icon: github
        href: https://github.com/mdanyalmalik
  google-analytics: "G-0C1TC199G5"
  
format:
  html:
    theme: lux
    css: styles.css

resources:
  CNAME

